Recommended system

In [1]:
# import libraties
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from google.colab import drive

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
# Reading ratings file from google drive. # the clean data
ratings = pd.read_csv('drive/MyDrive/clean_text.csv' , encoding='latin-1')
ratings.head()

Unnamed: 0                    id            brand  \
0           0  AV13O1A8GV-KLJ3akUyj  Universal Music   
1           1  AV14LG0R-jtxr-f38QfS         Lundberg   
2           2  AV14LG0R-jtxr-f38QfS         Lundberg   
3           3  AV16khLE-jtxr-f38VFn              K-Y   
4           4  AV16khLE-jtxr-f38VFn              K-Y   

                                          categories  \
0  Movies, Music & Books,Music,R&b,Movies & TV,Mo...   
1  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
2  Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
3  Personal Care,Medicine Cabinet,Lubricant/Sperm...   
4  Personal Care,Medicine Cabinet,Lubricant/Sperm...   

                         manufacturer  \
0  Universal Music Group / Cash Money   
1                            Lundberg   
2                            Lundberg   
3                                 K-Y   
4                                 K-Y   

                                         name              reviews_date  \
0   Pink Friday: Roman Reloaded Re-Up (w/dvd)  2012-11-30T06:21:45.000Z   
1  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
2  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
3            K-Y Love Sensuality Pleasure Gel  2016-01-06T00:00:00.000Z   
4            K-Y Love Sensuality Pleasure Gel  2016-12-21T00:00:00.000Z   

   reviews_rating                                       reviews_text  \
0               5  love album good hip hop side current pop sound...   
1               5   good flavor this review collected part promotion   
2               5                                        good flavor   
3               1  i read reviews looking buying one couples lubr...   
4               1  my husband bought gel us the gel caused irrita...   

  reviews_title reviews_username  user_sentiment  
0  Just Awesome           joshua               1  
1          Good        dorothy w               1  
2          Good        dorothy w               1  
3  Disappointed          rebecca               0  
4    Irritation        walker557               0

**Dividing the dataset into train and test**

In [5]:
# Test and Train split of the dataset.
train, test = train_test_split(ratings, test_size=0.30, random_state=31)

In [6]:
print(train.shape)
print(test.shape)

(20696, 12)
(8870, 12)


In [7]:
# Pivot the train ratings' dataset into matrix format in which columns are products and the rows are user names.
df_pivot = train.pivot_table(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
).fillna(0)

df_pivot.head(10)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          0.0               
01impala                                                        0.0               
02dakota                                                        0.0               
0325home                                                        0.0               
06stidriver                                                     0.0               
08dallas                                                        0.0               
09mommy11                                                       0.0               
1085                                                            0.0               
10ten                                                           0.0               
1143mom                                                         0.0               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            0.0   
01impala                                          0.0   
02dakota                                          0.0   
0325home                                          0.0   
06stidriver                                       0.0   
08dallas                                          5.0   
09mommy11                                         0.0   
1085                                              0.0   
10ten                                             0.0   
1143mom                                           0.0   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          0.0                   
01impala                                                        0.0                   
02dakota                                                        0.0                   
0325home                                                        0.0                   
06stidriver                                                     0.0                   
08dallas                                                        0.0                   
09mommy11                                                       0.0                   
1085                                                            0.0                   
10ten                                                           0.0                   
1143mom                                                         0.0                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               0.0   
01impala                                             0.0   
02dakota                                             0.0   
0325home                                             0.0   
06stidriver                                          0.0   
08dallas                                             0.0   
09mommy11                                            0.0   
1085                                                 0.0   
10ten                                                0.0   
1143mom                                              0.0   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      0.0   
01impala                                                    0.0   
02dakota                                                    0.0   
0325home                                                    0.0   
06stidriver                                                 0.0   
08dallas                                                    0.0   
09mommy11       

In [8]:
df_pivot.shape

(18061, 233)

# **`Creating dummy train & dummy test dataset`**

In [9]:
# Copy the train dataset into dummy_train
dummy_train = train.copy()

In [10]:
dummy_train.head(10)

Unnamed: 0                    id              brand  \
28900       29334  AVpfW8y_LJeJML437ySW      L'oreal Paris   
18491       18672  AVpfJP1C1cnluZ0-e3Xy             Clorox   
14423       14532  AVpf3VOfilAPnD_xjpun             Clorox   
24784       25152  AVpfPaoqLJeJML435Xk9  Warner Home Video   
9664         9773  AVpf3VOfilAPnD_xjpun             Clorox   
10335       10444  AVpf3VOfilAPnD_xjpun             Clorox   
26899       27296  AVpfRTh1ilAPnD_xYic2             Disney   
1564         1582  AVpe31o71cnluZ0-YrSD       Warner Bros.   
23444       23811  AVpfPaoqLJeJML435Xk9  Warner Home Video   
15812       15933  AVpf63aJLJeJML43F__Q        Burt's Bees   

                                              categories    manufacturer  \
28900  Beauty,Hair Care,Shampoo & Conditioner,Holiday...   L'oreal Paris   
18491  Household Chemicals,Household Cleaners,Bath & ...  AmazonUs/CLOO7   
14423  Household Essentials,Cleaning Supplies,Kitchen...          Clorox   
24784  Movies, Music & Books,Movies,Action & Adventur...            Test   
9664   Household Essentials,Cleaning Supplies,Kitchen...          Clorox   
10335  Household Essentials,Cleaning Supplies,Kitchen...          Clorox   
26899  Movies, Music & Books,Movies,Kids' & Family,Wa...     Walt Disney   
1564   Movies, Music & Books,Movies,Comedy,Movies & T...     TIME WARNER   
23444  Movies, Music & Books,Movies,Action & Adventur...            Test   
15812  Personal Care,Makeup,Lipstick, Lip Gloss, & Li...     Burt's Bees   

                                                    name  \
28900  L'or233al Paris Elvive Extraordinary Clay Reba...   
18491               Clorox Disinfecting Bathroom Cleaner   
14423  Clorox Disinfecting Wipes Value Pack Scented 1...   
24784  Godzilla 3d Includes Digital Copy Ultraviolet ...   
9664   Clorox Disinfecting Wipes Value Pack Scented 1...   
10335  Clorox Disinfecting Wipes Value Pack Scented 1...   
26899  Planes: Fire Rescue (2 Discs) (includes Digita...   
1564   Dark Shadows (includes Digital Copy) (ultravio...   
23444  Godzilla 3d Includes Digital Copy Ultraviolet ...   
15812                    Burt's Bees Lip Shimmer, Raisin   

                   reviews_date  reviews_rating  \
28900  2017-01-25T00:00:00.000Z               4   
18491  2012-01-27T00:00:00.000Z               4   
14423  2012-02-07T00:00:00.000Z               5   
24784  2014-09-22T00:00:00.000Z               5   
9664   2014-12-02T00:00:00.000Z               5   
10335  2013-04-16T00:00:00.000Z               5   
26899  2014-11-14T00:00:00.000Z               4   
1564   2016-04-09T00:00:00.000Z               4   
23444  2014-10-03T00:00:00.000Z               4   
15812  2014-09-24T00:00:00.000Z               5   

                                            reviews_text  \
28900  my hair incredibly dry due coloring constant s...   
18491  works great much better smell others gets stai...   
14423  by far favorite will never use another brand e...   
24784                             i bought movie awesome   
9664   clorox disinfecting wipes great van bucket soa...   
10335  i use product frequently it cleans well easy u...   
26899  another good disney addition sequel seemed lit...   
1564            thought movie excellent well worth money   
23444  although takes forever godzilla finally kick b...   
15812  i love nice color smooth feel highly recommend...   

                        reviews_title   reviews_username  user_sentiment  
28900            Great for Oily Roots      jhazobeaute23               1  
18491                           great              abret               1  
14423                      LOVE THESE            hgandee               1  
24784                   IT'S GODZILLA     bleepibityboop               1  
9664   Handy, stores in a small space             85lisa               1  
10335                  great product!              mel42               1  
26899                        Adorable  reluctantreviewer               1  
156

In [11]:
# The product not rated by user is marked as 1 for prediction. 
dummy_train['reviews_rating'] = dummy_train['reviews_rating'].apply(lambda x: 0 if x>=1 else 1)

In [12]:
# Convert the dummy train dataset into matrix format.
dummy_train = dummy_train.pivot_table(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
).fillna(1)

In [13]:
dummy_train.head(10)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          1.0               
01impala                                                        1.0               
02dakota                                                        1.0               
0325home                                                        1.0               
06stidriver                                                     1.0               
08dallas                                                        1.0               
09mommy11                                                       1.0               
1085                                                            1.0               
10ten                                                           1.0               
1143mom                                                         1.0               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            1.0   
01impala                                          1.0   
02dakota                                          1.0   
0325home                                          1.0   
06stidriver                                       1.0   
08dallas                                          0.0   
09mommy11                                         1.0   
1085                                              1.0   
10ten                                             1.0   
1143mom                                           1.0   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          1.0                   
01impala                                                        1.0                   
02dakota                                                        1.0                   
0325home                                                        1.0                   
06stidriver                                                     1.0                   
08dallas                                                        1.0                   
09mommy11                                                       1.0                   
1085                                                            1.0                   
10ten                                                           1.0                   
1143mom                                                         1.0                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               1.0   
01impala                                             1.0   
02dakota                                             1.0   
0325home                                             1.0   
06stidriver                                          1.0   
08dallas                                             1.0   
09mommy11                                            1.0   
1085                                                 1.0   
10ten                                                1.0   
1143mom                                              1.0   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      1.0   
01impala                                                    1.0   
02dakota                                                    1.0   
0325home                                                    1.0   
06stidriver                                                 1.0   
08dallas                                                    1.0   
09mommy11       

## **`Using Cosine Similarity`**

In [14]:
df_pivot.index.nunique()

18061

In [15]:
from sklearn.metrics.pairwise import pairwise_distances

# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_pivot, metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [16]:
user_correlation.shape

(18061, 18061)

# **Using adjusted Cosine**

### Here, we are not removing the NaN values and calculating the mean only for the Product rated by the user

In [17]:
# Create a user-product matrix.
df_pivot = train.pivot_table(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
)

In [18]:
df_pivot.shape

(18061, 233)

In [19]:
df_pivot.head(10)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          NaN               
01impala                                                        NaN               
02dakota                                                        NaN               
0325home                                                        NaN               
06stidriver                                                     NaN               
08dallas                                                        NaN               
09mommy11                                                       NaN               
1085                                                            NaN               
10ten                                                           NaN               
1143mom                                                         NaN               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            NaN   
01impala                                          NaN   
02dakota                                          NaN   
0325home                                          NaN   
06stidriver                                       NaN   
08dallas                                          5.0   
09mommy11                                         NaN   
1085                                              NaN   
10ten                                             NaN   
1143mom                                           NaN   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          NaN                   
01impala                                                        NaN                   
02dakota                                                        NaN                   
0325home                                                        NaN                   
06stidriver                                                     NaN                   
08dallas                                                        NaN                   
09mommy11                                                       NaN                   
1085                                                            NaN                   
10ten                                                           NaN                   
1143mom                                                         NaN                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               NaN   
01impala                                             NaN   
02dakota                                             NaN   
0325home                                             NaN   
06stidriver                                          NaN   
08dallas                                             NaN   
09mommy11                                            NaN   
1085                                                 NaN   
10ten                                                NaN   
1143mom                                              NaN   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      NaN   
01impala                                                    NaN   
02dakota                                                    NaN   
0325home                                                    NaN   
06stidriver                                                 NaN   
08dallas                                                    NaN   
09mommy11       

### Normalising the rating of the product for each user around 0 mean

In [20]:
mean = np.nanmean(df_pivot, axis=1)
print(mean)
df_subtracted = (df_pivot.T-mean).T

[4. 3. 5. ... 4. 5. 5.]


In [21]:
df_subtracted.head(10)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          NaN               
01impala                                                        NaN               
02dakota                                                        NaN               
0325home                                                        NaN               
06stidriver                                                     NaN               
08dallas                                                        NaN               
09mommy11                                                       NaN               
1085                                                            NaN               
10ten                                                           NaN               
1143mom                                                         NaN               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            NaN   
01impala                                          NaN   
02dakota                                          NaN   
0325home                                          NaN   
06stidriver                                       NaN   
08dallas                                          0.0   
09mommy11                                         NaN   
1085                                              NaN   
10ten                                             NaN   
1143mom                                           NaN   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          NaN                   
01impala                                                        NaN                   
02dakota                                                        NaN                   
0325home                                                        NaN                   
06stidriver                                                     NaN                   
08dallas                                                        NaN                   
09mommy11                                                       NaN                   
1085                                                            NaN                   
10ten                                                           NaN                   
1143mom                                                         NaN                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               NaN   
01impala                                             NaN   
02dakota                                             NaN   
0325home                                             NaN   
06stidriver                                          NaN   
08dallas                                             NaN   
09mommy11                                            NaN   
1085                                                 NaN   
10ten                                                NaN   
1143mom                                              NaN   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      NaN   
01impala                                                    NaN   
02dakota                                                    NaN   
0325home                                                    NaN   
06stidriver                                                 NaN   
08dallas                                                    NaN   
09mommy11       

### Finding cosine similarity

In [22]:
from sklearn.metrics.pairwise import pairwise_distances

In [23]:
# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [24]:
user_correlation.shape

(18061, 18061)

## Prediction - User User

Doing the prediction for the users which are positively related with other users, and not the users which are negatively related as we are interested in the users which are more similar to the current users. So, ignoring the correlation for values less than 0. 

In [25]:
user_correlation[user_correlation<0]=0
user_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Rating predicted by the user (for product rated as well as not rated) is the weighted sum of correlation with the product rating (as present in the rating dataset). 

In [26]:
#this is dot product btw corelated matrix and user-iiem matrix
user_predicted_ratings = np.dot(user_correlation, df_pivot.fillna(0))
user_predicted_ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [27]:
user_predicted_ratings.shape

(18061, 233)

In [28]:
user_predicted_ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Since we are interested only in the products not rated by the user, we will ignore the products rated by the user by making it zero. 

In [29]:
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head(10)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          0.0               
01impala                                                        0.0               
02dakota                                                        0.0               
0325home                                                        0.0               
06stidriver                                                     0.0               
08dallas                                                        0.0               
09mommy11                                                       0.0               
1085                                                            0.0               
10ten                                                           0.0               
1143mom                                                         0.0               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            0.0   
01impala                                          0.0   
02dakota                                          0.0   
0325home                                          0.0   
06stidriver                                       0.0   
08dallas                                          0.0   
09mommy11                                         0.0   
1085                                              0.0   
10ten                                             0.0   
1143mom                                           0.0   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          0.0                   
01impala                                                        0.0                   
02dakota                                                        0.0                   
0325home                                                        0.0                   
06stidriver                                                     0.0                   
08dallas                                                        0.0                   
09mommy11                                                       0.0                   
1085                                                            0.0                   
10ten                                                           0.0                   
1143mom                                                         0.0                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               0.0   
01impala                                             0.0   
02dakota                                             0.0   
0325home                                             0.0   
06stidriver                                          0.0   
08dallas                                             0.0   
09mommy11                                            0.0   
1085                                                 0.0   
10ten                                                0.0   
1143mom                                              0.0   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      0.0   
01impala                                                    0.0   
02dakota                                                    0.0   
0325home                                                    0.0   
06stidriver                                                 0.0   
08dallas                                                    0.0   
09mommy11       

### Finding the top 5 recommendation for the *user*

In [30]:
# Take the user ID as input.
user_input = input("Enter your user name")
print(user_input)

Enter your user name08dallas
08dallas


In [31]:
user_final_rating.head(7)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          0.0               
01impala                                                        0.0               
02dakota                                                        0.0               
0325home                                                        0.0               
06stidriver                                                     0.0               
08dallas                                                        0.0               
09mommy11                                                       0.0               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            0.0   
01impala                                          0.0   
02dakota                                          0.0   
0325home                                          0.0   
06stidriver                                       0.0   
08dallas                                          0.0   
09mommy11                                         0.0   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          0.0                   
01impala                                                        0.0                   
02dakota                                                        0.0                   
0325home                                                        0.0                   
06stidriver                                                     0.0                   
08dallas                                                        0.0                   
09mommy11                                                       0.0                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               0.0   
01impala                                             0.0   
02dakota                                             0.0   
0325home                                             0.0   
06stidriver                                          0.0   
08dallas                                             0.0   
09mommy11                                            0.0   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      0.0   
01impala                                                    0.0   
02dakota                                                    0.0   
0325home                                                    0.0   
06stidriver                                                 0.0   
08dallas                                                    0.0   
09mommy11                                                   0.0   

name              4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
reviews_username                                                      
00dog3                                                          0.0   
01impala                                                        0.0   
02dakota                                                        0.0   
0325home                                                        0.0   
06stidriver                                                     0.0   
08dallas                                                        0.0   
09mommy11                                                       0.0   

name              Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
reviews_username                                                                
00dog3 

In [32]:
d = user_final_rating.loc[user_input].sort_values(ascending=False)[0:5]
d

name
Yes To Grapefruit Rejuvenating Body Wash                                    0.0
Fiskars174 Classic Stick Rotary Cutter (45 Mm)                              0.0
Holmes174 Personal Indoor Heater W/ Manual Controls White 1500w Hfh131-N    0.0
Hollywood Beauty Olive Cholesterol                                          0.0
High-Dome Floor Door Stop                                                   0.0
Name: 08dallas, dtype: float64

# Evaluation - User User 

Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the product already rated by the user insead of predicting it for the product not rated by the user. 

In [33]:
# Find out the common users of test and train dataset.
common = test[test.reviews_username.isin(train.reviews_username)]
common.shape

(2026, 12)

In [34]:
common.head(10)

Unnamed: 0                    id              brand  \
17231       17353  AVpfazX31cnluZ0-kbdl       Just For Men   
8442         8539  AVpf3VOfilAPnD_xjpun             Clorox   
26260       26646  AVpfPPkEilAPnD_xX3cP             Aveeno   
28569       29003  AVpfW8y_LJeJML437ySW      L'oreal Paris   
8554         8651  AVpf3VOfilAPnD_xjpun             Clorox   
12493       12602  AVpf3VOfilAPnD_xjpun             Clorox   
18559       18740  AVpfJP1C1cnluZ0-e3Xy             Clorox   
18232       18388  AVpfGuDrLJeJML432fDz    Pleasant Hearth   
23239       23606  AVpfPaoqLJeJML435Xk9  Warner Home Video   
18869       19050  AVpfJP1C1cnluZ0-e3Xy             Clorox   

                                              categories        manufacturer  \
17231  Personal Care,Hair Care,Hair Color And Bleachi...  Combe Incorporated   
8442   Household Essentials,Cleaning Supplies,Kitchen...              Clorox   
26260  Personal Care,Sun Care,Featured Brands,Health ...         Aveeno Baby   
28569  Beauty,Hair Care,Shampoo & Conditioner,Holiday...       L'oreal Paris   
8554   Household Essentials,Cleaning Supplies,Kitchen...              Clorox   
12493  Household Essentials,Cleaning Supplies,Kitchen...              Clorox   
18559  Household Chemicals,Household Cleaners,Bath & ...      AmazonUs/CLOO7   
18232  Home,Home Appliances,Fireplaces & Accessories,...     GHP Group, Inc.   
23239  Movies, Music & Books,Movies,Action & Adventur...                Test   
18869  Household Chemicals,Household Cleaners,Bath & ...      AmazonUs/CLOO7   

                                                    name  \
17231  Just For Men Touch Of Gray Gray Hair Treatment...   
8442   Clorox Disinfecting Wipes Value Pack Scented 1...   
26260  Aveeno Baby Continuous Protection Lotion Sunsc...   
28569  L'or233al Paris Elvive Extraordinary Clay Reba...   
8554   Clorox Disinfecting Wipes Value Pack Scented 1...   
12493  Clorox Disinfecting Wipes Value Pack Scented 1...   
18559               Clorox Disinfecting Bathroom Cleaner   
18232  Pleasant Hearth Diamond Fireplace Screen - Esp...   
23239  Godzilla 3d Includes Digital Copy Ultraviolet ...   
18869               Clorox Disinfecting Bathroom Cleaner   

                   reviews_date  reviews_rating  \
17231  2012-02-20T00:00:00.000Z               4   
8442   2013-04-02T22:16:49.000Z               5   
26260  2016-12-09T00:00:00.000Z               5   
28569  2017-01-17T23:06:48.000Z               3   
8554   2012-01-21T15:36:44.000Z               5   
12493  2012-02-05T00:00:00.000Z               5   
18559  2012-02-11T00:00:00.000Z               4   
18232  2014-10-26T00:00:00.000Z               5   
23239  2017-07-14T00:00:00.000Z               4   
18869  2012-01-25T00:00:00.000Z               5   

                                            reviews_text  \
17231  i love leave gray make hair look natural is to...   
8442                          love ready use go anywhere   
26260                                               good   
28569  i received product influenster testing review ...   
8554   this best product quick daily wipe outside toilet   
12493  i love wipes they smell good along disinfectin...   
18559  i really like smell clean look i get tub sink ...   
18232  this screen fits opening perfectly saying some...   
23239  good transfer bought movie due pending king ko...   
18869          these wipes great i use time get job done   

                                           reviews_title   reviews_username  \
17231  It s is very good .I make my hair look natural...             mars57   
8442                                          Convenient             nitmom   
26260                                         Five Stars  byamazon customer   
28569                    Not As Nourishing As I Expected             ivywxy   
8554                                   Bathroom Cleaning            bonnieo   
12493                                      great product             stevie   
18559 

In [35]:
# convert into the user-product matrix.
common_user_based_matrix = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating')

In [36]:
common_user_based_matrix.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
1234                                                            NaN               
1234567                                                         NaN               
1943                                                            NaN               
1witch                                                          NaN               
37f5p                                                           NaN               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
1234                                              NaN   
1234567                                           NaN   
1943                                              NaN   
1witch                                            NaN   
37f5p                                             5.0   

name              All,bran Complete Wheat Flakes, 18 Oz.  \
reviews_username                                           
1234                                                 NaN   
1234567                                              NaN   
1943                                                 NaN   
1witch                                               NaN   
37f5p                                                NaN   

name              Aussie Aussome Volume Shampoo, 13.5 Oz  \
reviews_username                                           
1234                                                 NaN   
1234567                                              NaN   
1943                                                 NaN   
1witch                                               NaN   
37f5p                                                NaN   

name              Australian Gold Exotic Blend Lotion, SPF 4  \
reviews_username                                               
1234                                                     NaN   
1234567                                                  NaN   
1943                                                     NaN   
1witch                                                   NaN   
37f5p                                                    NaN   

name              Aveeno Baby Continuous Protection Lotion Sunscreen with Broad Spectrum SPF 55, 4oz  \
reviews_username                                                                                       
1234                                                            NaN                                    
1234567                                                         NaN                                    
1943                                                            NaN                                    
1witch                                                          NaN                                    
37f5p                                                           NaN                                    

name              Avery174 Ready Index Contemporary Table Of Contents Divider, 1-8, Multi, Letter  \
reviews_username                                                                                    
1234                                                            NaN                                 
1234567                                                         NaN                                 
1943                                                            5.0                                 
1witch                                                          NaN                                 
37f5p                                                           NaN                                 

name              Axe Dry Anti-Perspirant Deodorant Invisible Solid Phoenix  \
reviews_username                                                              
1234                                                            NaN           
1234567                                              

In [37]:
# Convert the user_correlation matrix into dataframe.
user_correlation_df = pd.DataFrame(user_correlation)

In [38]:
user_correlation_df.head(10)

Output hidden; open in https://colab.research.google.com to view.

In [39]:
df_subtracted.head(1)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          NaN               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            NaN   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          NaN                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               NaN   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      NaN   

name              4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
reviews_username                                                      
00dog3                                                          NaN   

name              Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
reviews_username                                                                
00dog3                                                          NaN             

name              Alberto VO5 Salon Series Smooth Plus Sleek Shampoo  \
reviews_username                                                       
00dog3                                                          NaN    

name              All,bran Complete Wheat Flakes, 18 Oz.  \
reviews_username                                           
00dog3                                               NaN   

name              Ambi Complexion Cleansing Bar  \
reviews_username                                  
00dog3                                      NaN   

name              Annie's Homegrown Deluxe Elbows & Four Cheese Sauce  \
reviews_username                                                        
00dog3                                                          NaN     

name              Annie's Homegrown Gluten Free Double Chocolate Chip Granola Bars  \
reviews_username                                                                     
00dog3                                                          NaN                  

name              Arrid Extra Dry Anti-Perspirant Deodorant Spray Regular  \
reviews_username                                                            
00dog3                                                          NaN         

name              Aussie Aussome Volume Shampoo, 13.5 Oz  \
reviews_username                                           
00dog3                                               NaN   

name              Australian Gold Exotic Blend Lotion, SPF 4  \
reviews_username                                               
00dog3                                                   NaN   

name              Aveeno Baby Continuous Protection Lotion Sunscreen with Broad Spectrum SPF 55, 4oz  \
reviews_username                                                                                       
00dog3                                                          NaN                                    

name              Avery174 Ready Index Contemporary Table Of Contents Divider, 1-8, Multi, Letter  \
reviews_username                                                                                    
00dog3                                                          NaN                                 

name              Axe Dry Anti-Perspirant Deodorant Invisible Solid Phoenix  \
reviews_username                                                              
00dog3                                                         

In [40]:
user_correlation_df['reviews_username'] = df_subtracted.index

user_correlation_df.set_index('reviews_username',inplace=True)
user_correlation_df.head()

Output hidden; open in https://colab.research.google.com to view.

In [41]:
common.head(1)

Unnamed: 0                    id         brand  \
17231       17353  AVpfazX31cnluZ0-kbdl  Just For Men   

                                              categories        manufacturer  \
17231  Personal Care,Hair Care,Hair Color And Bleachi...  Combe Incorporated   

                                                    name  \
17231  Just For Men Touch Of Gray Gray Hair Treatment...   

                   reviews_date  reviews_rating  \
17231  2012-02-20T00:00:00.000Z               4   

                                            reviews_text  \
17231  i love leave gray make hair look natural is to...   

                                           reviews_title reviews_username  \
17231  It s is very good .I make my hair look natural...           mars57   

       user_sentiment  
17231               1

In [42]:
list_name = common.reviews_username.tolist()

user_correlation_df.columns = df_subtracted.index.tolist()


user_correlation_df_1 =  user_correlation_df[user_correlation_df.index.isin(list_name)]

In [43]:
user_correlation_df_1.shape

(1698, 18061)

In [44]:
user_correlation_df_2 = user_correlation_df_1.T[user_correlation_df_1.T.index.isin(list_name)]

In [45]:
user_correlation_df_3 = user_correlation_df_2.T

In [46]:
user_correlation_df_3.head()

1234  1234567  1943  1witch  37f5p  4cloroxl  4djs  \
reviews_username                                                       
1234               1.0      0.0   0.0     0.0    0.0       0.0   0.0   
1234567            0.0      0.0   0.0     0.0    0.0       0.0   0.0   
1943               0.0      0.0   0.0     0.0    0.0       0.0   0.0   
1witch             0.0      0.0   0.0     0.0    0.0       0.0   0.0   
37f5p              0.0      0.0   0.0     0.0    0.0       0.0   0.0   

                  8ellie24  aac06002  aaron  abby  abc  abcdef  abcgator  \
reviews_username                                                           
1234                   0.0       0.0    0.0   0.0  0.0     0.0       0.0   
1234567                0.0       0.0    0.0   0.0  0.0     0.0       0.0   
1943                   0.0       0.0    0.0   0.0  0.0     0.0       0.0   
1witch                 0.0       0.0    0.0   0.0  0.0     0.0       0.0   
37f5p                  0.0       0.0    0.0   0.0  0.0     0.0       0.0   

                  abcssds  abismomy  abret  ace24  acg1  acv4217      adam  \
reviews_username                                                             
1234                  0.0       0.0    0.0    0.0   0.0      0.0  0.333333   
1234567               0.0       0.0    0.0    0.0   0.0      0.0  0.000000   
1943                  0.0       0.0    0.0    0.0   0.0      0.0  0.000000   
1witch                0.0       0.0    0.0    0.0   0.0      0.0  0.000000   
37f5p                 0.0       0.0    0.0    0.0   0.0      0.0  0.000000   

                  adamsmom  adelynsmom  adizzione  adriana  adriana9999  \
reviews_username                                                          
1234                   0.0         0.0        0.0      0.0          0.0   
1234567                0.0         0.0        0.0      0.0          0.0   
1943                   0.0         0.0        0.0      0.0          0.0   
1witch                 0.0         0.0        0.0      0.0          0.0   
37f5p                  0.0         0.0        0.0      0.0          0.0   

                  aep1010  agmt  ahjohnson1983  aimee  aisha  aj1135  ajay  \
reviews_username                                                             
1234                  0.0   0.0            0.0    0.0    0.0     0.0   0.0   
1234567               0.0   0.0            0.0    0.0    0.0     0.0   0.0   
1943                  0.0   0.0            0.0    0.0    0.0     0.0   0.0   
1witch                0.0   0.0            0.0    0.0    0.0     0.0   0.0   
37f5p                 0.0   0.0            0.0    0.0    0.0     0.0   0.0   

                  ajcrossover11  ajune  akporter84  aktcharlotte  alarm  \
reviews_username                                                          
1234                        0.0    0.0         0.0           0.0    0.0   
1234567                     0.0    0.0         0.0           0.0    0.0   
1943                        0.0    0.0         0.0           0.0    0.0   
1witch                      0.0    0.0         0.0           0.0    0.0   
37f5p                       0.0    0.0         0.0           0.0    0.0   

                  alena125  alex  ali1353  alice  alix p  allan6048  allie123  \
reviews_username                                                                
1234                   0.0   0.0      0.0    0.0     0.0        0.0       0.0   
1234567                0.0   0.0      0.0    0.0     0.0        0.0       0.0   
1943                   0.0   0.0      0.0    0.0     0.0        0.0       0.0   
1witch                 0.0   0.0      0.0    0.0     0.0        0.0       0.0   
37f5p                  0.0   0.0      0.0    0.0     0.0        0.0       0.0   

                  allison33  ally  allyj1984  alredhouse  alta  alvin  amanda  \
reviews_username                                                                
1234                    0.0   0.0        0.0         0.0   0.0    0.0     0.0   
1234567                

In [47]:
user_correlation_df_3.shape

(1698, 1698)

In [48]:
user_correlation_df_3[user_correlation_df_3<0]=0

common_user_predicted_ratings = np.dot(user_correlation_df_3, common_user_based_matrix.fillna(0))
common_user_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 1.15470054, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75201365, 0.        , ..., 2.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [49]:
dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='name', values='reviews_rating').fillna(0)

In [50]:
dummy_test.shape

(1698, 111)

In [51]:
common_user_based_matrix.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
1234                                                            NaN               
1234567                                                         NaN               
1943                                                            NaN               
1witch                                                          NaN               
37f5p                                                           NaN               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
1234                                              NaN   
1234567                                           NaN   
1943                                              NaN   
1witch                                            NaN   
37f5p                                             5.0   

name              All,bran Complete Wheat Flakes, 18 Oz.  \
reviews_username                                           
1234                                                 NaN   
1234567                                              NaN   
1943                                                 NaN   
1witch                                               NaN   
37f5p                                                NaN   

name              Aussie Aussome Volume Shampoo, 13.5 Oz  \
reviews_username                                           
1234                                                 NaN   
1234567                                              NaN   
1943                                                 NaN   
1witch                                               NaN   
37f5p                                                NaN   

name              Australian Gold Exotic Blend Lotion, SPF 4  \
reviews_username                                               
1234                                                     NaN   
1234567                                                  NaN   
1943                                                     NaN   
1witch                                                   NaN   
37f5p                                                    NaN   

name              Aveeno Baby Continuous Protection Lotion Sunscreen with Broad Spectrum SPF 55, 4oz  \
reviews_username                                                                                       
1234                                                            NaN                                    
1234567                                                         NaN                                    
1943                                                            NaN                                    
1witch                                                          NaN                                    
37f5p                                                           NaN                                    

name              Avery174 Ready Index Contemporary Table Of Contents Divider, 1-8, Multi, Letter  \
reviews_username                                                                                    
1234                                                            NaN                                 
1234567                                                         NaN                                 
1943                                                            5.0                                 
1witch                                                          NaN                                 
37f5p                                                           NaN                                 

name              Axe Dry Anti-Perspirant Deodorant Invisible Solid Phoenix  \
reviews_username                                                              
1234                                                            NaN           
1234567                                              

In [52]:
dummy_test.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
1234                                                            0.0               
1234567                                                         0.0               
1943                                                            0.0               
1witch                                                          0.0               
37f5p                                                           0.0               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
1234                                              0.0   
1234567                                           0.0   
1943                                              0.0   
1witch                                            0.0   
37f5p                                             1.0   

name              All,bran Complete Wheat Flakes, 18 Oz.  \
reviews_username                                           
1234                                                 0.0   
1234567                                              0.0   
1943                                                 0.0   
1witch                                               0.0   
37f5p                                                0.0   

name              Aussie Aussome Volume Shampoo, 13.5 Oz  \
reviews_username                                           
1234                                                 0.0   
1234567                                              0.0   
1943                                                 0.0   
1witch                                               0.0   
37f5p                                                0.0   

name              Australian Gold Exotic Blend Lotion, SPF 4  \
reviews_username                                               
1234                                                     0.0   
1234567                                                  0.0   
1943                                                     0.0   
1witch                                                   0.0   
37f5p                                                    0.0   

name              Aveeno Baby Continuous Protection Lotion Sunscreen with Broad Spectrum SPF 55, 4oz  \
reviews_username                                                                                       
1234                                                            0.0                                    
1234567                                                         0.0                                    
1943                                                            0.0                                    
1witch                                                          0.0                                    
37f5p                                                           0.0                                    

name              Avery174 Ready Index Contemporary Table Of Contents Divider, 1-8, Multi, Letter  \
reviews_username                                                                                    
1234                                                            0.0                                 
1234567                                                         0.0                                 
1943                                                            1.0                                 
1witch                                                          0.0                                 
37f5p                                                           0.0                                 

name              Axe Dry Anti-Perspirant Deodorant Invisible Solid Phoenix  \
reviews_username                                                              
1234                                                            0.0           
1234567                                              

In [53]:
common_user_predicted_ratings = np.multiply(common_user_predicted_ratings,dummy_test)

In [54]:
common_user_predicted_ratings.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
1234                                                            0.0               
1234567                                                         0.0               
1943                                                            0.0               
1witch                                                          0.0               
37f5p                                                           0.0               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
1234                                              0.0   
1234567                                           0.0   
1943                                              0.0   
1witch                                            0.0   
37f5p                                             0.0   

name              All,bran Complete Wheat Flakes, 18 Oz.  \
reviews_username                                           
1234                                                 0.0   
1234567                                              0.0   
1943                                                 0.0   
1witch                                               0.0   
37f5p                                                0.0   

name              Aussie Aussome Volume Shampoo, 13.5 Oz  \
reviews_username                                           
1234                                                 0.0   
1234567                                              0.0   
1943                                                 0.0   
1witch                                               0.0   
37f5p                                                0.0   

name              Australian Gold Exotic Blend Lotion, SPF 4  \
reviews_username                                               
1234                                                     0.0   
1234567                                                  0.0   
1943                                                     0.0   
1witch                                                   0.0   
37f5p                                                    0.0   

name              Aveeno Baby Continuous Protection Lotion Sunscreen with Broad Spectrum SPF 55, 4oz  \
reviews_username                                                                                       
1234                                                            0.0                                    
1234567                                                         0.0                                    
1943                                                            0.0                                    
1witch                                                          0.0                                    
37f5p                                                           0.0                                    

name              Avery174 Ready Index Contemporary Table Of Contents Divider, 1-8, Multi, Letter  \
reviews_username                                                                                    
1234                                                            0.0                                 
1234567                                                         0.0                                 
1943                                                            0.0                                 
1witch                                                          0.0                                 
37f5p                                                           0.0                                 

name              Axe Dry Anti-Perspirant Deodorant Invisible Solid Phoenix  \
reviews_username                                                              
1234                                                            0.0           
1234567                                              

Calculating the RMSE for only the products rated by user. For RMSE, normalising the rating to (1,5) range.

In [55]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_user_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:461: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:462: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [56]:
common_ = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating')

In [57]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [58]:
rmse = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse)

2.552016092469094


## Using Item similarity

# Item Based Similarity

Taking the transpose of the rating matrix to normalize the rating around the mean for different Product Name. In the user based similarity, we had taken mean for each user instead of each product. 

In [59]:
df_pivot = train.pivot_table(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
).T

df_pivot.head()

Output hidden; open in https://colab.research.google.com to view.

Normalising the product rating for each product for using the Adujsted Cosine

In [60]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [61]:
df_subtracted.head()

Output hidden; open in https://colab.research.google.com to view.

Finding the cosine similarity using pairwise distances approach

In [62]:
from sklearn.metrics.pairwise import pairwise_distances

In [63]:
# Item Similarity Matrix
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [64]:
item_correlation.shape

(233, 233)

Filtering the correlation only for which the value is greater than 0. (Positively correlated)

In [65]:
item_correlation[item_correlation<0]=0
item_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# Prediction - Item Item

In [66]:
item_predicted_ratings = np.dot((df_pivot.fillna(0).T),item_correlation)
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.02023095, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00266585,
        0.01153398],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00444308,
        0.01922331],
       ...,
       [0.        , 0.00177756, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.00818635, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.03585012, 0.        ,
        0.        ]])

In [67]:
item_predicted_ratings.shape

(18061, 233)

In [68]:
dummy_train.shape

(18061, 233)

### Filtering the rating only for the proudcts not rated by the user for recommendation

In [69]:
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
reviews_username                                                                  
00dog3                                                          0.0               
01impala                                                        0.0               
02dakota                                                        0.0               
0325home                                                        0.0               
06stidriver                                                     0.0               

name              100:Complete First Season (blu-Ray)  \
reviews_username                                        
00dog3                                            0.0   
01impala                                          0.0   
02dakota                                          0.0   
0325home                                          0.0   
06stidriver                                       0.0   

name              2017-2018 Brownline174 Duraflex 14-Month Planner 8 1/2 X 11 Black  \
reviews_username                                                                      
00dog3                                                          0.0                   
01impala                                                        0.0                   
02dakota                                                        0.0                   
0325home                                                        0.0                   
06stidriver                                                     0.0                   

name              2x Ultra Era with Oxi Booster, 50fl oz  \
reviews_username                                           
00dog3                                               0.0   
01impala                                             0.0   
02dakota                                             0.0   
0325home                                             0.0   
06stidriver                                          0.0   

name              42 Dual Drop Leaf Table with 2 Madrid Chairs"  \
reviews_username                                                  
00dog3                                                      0.0   
01impala                                                    0.0   
02dakota                                                    0.0   
0325home                                                    0.0   
06stidriver                                                 0.0   

name              4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
reviews_username                                                      
00dog3                                                          0.0   
01impala                                                        0.0   
02dakota                                                        0.0   
0325home                                                        0.0   
06stidriver                                                     0.0   

name              Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
reviews_username                                                                
00dog3                                                          0.0             
01impala                                                        0.0             
02dakota                                                        0.0             
0325home                                                        0.0             
06stidriver                                                     0.0             

name              Alberto VO5 Salon Series Smooth Plus Sleek Shampoo  \
reviews_username                                                       
00dog3                                                          0.0    
01impala                                                        0.0    
02dakota                                                        0.0    
0325home                                                        0.0    
06stidriver        

In [70]:
#Dumping to pickle file
import pickle
pickle.dump(item_final_rating, open('drive/MyDrive/itembased-df.pickle', 'wb'))

### Finding the top 5 recommendation for the *user*

In [71]:
# Take the user ID as input
user_input = input("Enter your user name")
print(user_input)

Enter your user name08dallas
08dallas


In [72]:
# Recommending the Top 5 products to the user.
d = item_final_rating.loc[user_input].sort_values(ascending=False)[0:5]
d

name
Dark Shadows (includes Digital Copy) (ultraviolet) (dvdvideo)    0.018195
The Resident Evil Collection 5 Discs (blu-Ray)                   0.012720
Stargate (ws) (ultimate Edition) (director's Cut) (dvdvideo)     0.012505
Coty Airspun Face Powder, Translucent Extra Coverage             0.010145
Red (special Edition) (dvdvideo)                                 0.008186
Name: 08dallas, dtype: float64

# Evaluation - Item Item

Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the product already rated by the user insead of predicting it for the product not rated by the user. 

In [73]:
test.columns

Index(['Unnamed: 0', 'id', 'brand', 'categories', 'manufacturer', 'name',
       'reviews_date', 'reviews_rating', 'reviews_text', 'reviews_title',
       'reviews_username', 'user_sentiment'],
      dtype='object')

In [74]:
common =  test[test.name.isin(train.name)]
common.shape

(8851, 12)

In [75]:
common.head(4)

Unnamed: 0                    id                 brand  \
132           132  AV1l8zRZvKc47QAVhnAv                  Olay   
5794         5882  AVpf2tw1ilAPnD_xjflC  Summit Entertainment   
17231       17353  AVpfazX31cnluZ0-kbdl          Just For Men   
15240       15361  AVpf5FF71cnluZ0-tHAV                Orajel   

                                              categories  \
132    Personal Care,Skin Care,Anti-Aging,Beauty,Face...   
5794   Movies & TV Shows,Instawatch Movies By VUDU,Sh...   
17231  Personal Care,Hair Care,Hair Color And Bleachi...   
15240  Personal Care,Oral Care,Oral Pain Relief,Child...   

               manufacturer  \
132                     P&G   
5794   Summit Entertainment   
17231    Combe Incorporated   
15240                Orajel   

                                                    name  \
132    Olay Regenerist Deep Hydration Regenerating Cream   
5794                    Red (special Edition) (dvdvideo)   
17231  Just For Men Touch Of Gray Gray Hair Treatment...   
15240  Orajel Maximum Strength Toothache Pain Relief ...   

                   reviews_date  reviews_rating  \
132    2016-06-01T00:00:00.000Z               4   
5794   2014-01-03T00:00:00.000Z               5   
17231  2012-02-20T00:00:00.000Z               4   
15240  2017-02-21T00:00:00.000Z               5   

                                            reviews_text  \
132    it smell amazing feels great skin leave feelin...   
5794   great movie great plot great price its great m...   
17231  i love leave gray make hair look natural is to...   
15240  i toothache one night thought i would try oraj...   

                                           reviews_title reviews_username  \
132                                           6623443094       6623443094   
5794                                         Great movie             bbmj   
17231  It s is very good .I make my hair look natural...           mars57   
15240                                    Awesome Product            tjs38   

       user_sentiment  
132                 1  
5794                1  
17231               1  
15240               1

In [76]:
common_item_based_matrix = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating').T

In [77]:
common_item_based_matrix.shape

(176, 8250)

In [78]:
item_correlation_df = pd.DataFrame(item_correlation)

In [79]:
item_correlation_df.head(1)

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14   \
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   90   91   92   93   94   95   96   97   98   99   100  101  102  103  104  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   105  106  107  108  109  110  111  112  113  114  115  116  117  118  119  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   120  121  122  123  124  125  126  127  128  129  130  131  132  133  134  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   135  136  137  138  139  140  141  142  143  144  145  146  147  148  149  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   150  151  152  153  154  155  156  157  158  159  160  161  162  163  164  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   165  166  167  168  169  170  171  172  173  174  175  176  177  178  179  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   180  181  182  183  184  185  186  187  188  189  190  191  192  193  194  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   195  196  197  198  199  200  201  202  203  204  205  206  207  208  209  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   210  211  212  213  214  215  216  217  218  219  220  221  222  223  224  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   225  226  227  228  229  230  231  232  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [80]:
item_correlation_df['name'] = df_subtracted.index
item_correlation_df.set_index('name',inplace=True)
item_correlation_df.head()

0    1    2    3    4    \
name                                                                          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  1.0  0.0  0.0  0.0  0.0   
100:Complete First Season (blu-Ray)                 0.0  1.0  0.0  0.0  0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  0.0  0.0  0.0   
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  0.0  0.0  0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  0.0  0.0  0.0  0.0   

                                                    5    6    7    8    9    \
name                                                                          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  0.0  0.0  0.0  0.0  0.0   
100:Complete First Season (blu-Ray)                 0.0  0.0  0.0  0.0  0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  0.0  0.0  0.0   
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  0.0  0.0  0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  0.0  0.0  0.0  0.0   

                                                    10   11   12   13   14   \
name                                                                          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  0.0  0.0  0.0  0.0  0.0   
100:Complete First Season (blu-Ray)                 0.0  0.0  0.0  0.0  0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  0.0  0.0  0.0   
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  0.0  0.0  0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  0.0  0.0  0.0  0.0   

                                                    15   16   17   18   19   \
name                                                                          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  0.0  0.0  0.0  0.0  0.0   
100:Complete First Season (blu-Ray)                 0.0  0.0  0.0  0.0  0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  0.0  0.0  0.0   
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  0.0  0.0  0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  0.0  0.0  0.0  0.0   

                                                    20   21   22   23   24   \
name                                                                          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  0.0  0.0  0.0  0.0  0.0   
100:Complete First Season (blu-Ray)                 0.0  0.0  0.0  0.0  0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  0.0  0.0  0.0   
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  0.0  0.0  0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  0.0  0.0  0.0  0.0   

                                                    25   26   27   28   29   \
name                                                                          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  0.0  0.0  0.0  0.0  0.0   
100:Complete First Season (blu-Ray)                 0.0  0.0  0.0  0.0  0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  0.0  0.0  0.0   
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  0.0  0.0  0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  0.0  0.0  0.0  0.0   

                                                    30   31   32   33   34   \
name                                                                          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  0.0  0.0  0.0  0.0  0.0   
100:Complete First Season (blu-Ray)                 0.0  0.0  0.0  0.0  0.0   
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  0.0  0.0  0.0   
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  0.0  0.0  0.0   
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  0.0  0.0  0.0  0.0   

                                                    35   36   37   38   39   \
name                                                                          
0.6 Cu. Ft. Lett

In [81]:
list_name = common.name.tolist()

In [82]:
item_correlation_df.columns = df_subtracted.index.tolist()

item_correlation_df_1 =  item_correlation_df[item_correlation_df.index.isin(list_name)]

In [83]:
item_correlation_df_2 = item_correlation_df_1.T[item_correlation_df_1.T.index.isin(list_name)]

item_correlation_df_3 = item_correlation_df_2.T

In [84]:
item_correlation_df_3.head()

0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  \
name                                                                                                                
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                                1.0               
100:Complete First Season (blu-Ray)                                                               0.0               
2x Ultra Era with Oxi Booster, 50fl oz                                                            0.0               
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                                 0.0               
Africa's Best No-Lye Dual Conditioning Relaxer ...                                                0.0               

                                                    100:Complete First Season (blu-Ray)  \
name                                                                                      
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                  0.0   
100:Complete First Season (blu-Ray)                                                 1.0   
2x Ultra Era with Oxi Booster, 50fl oz                                              0.0   
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                   0.0   
Africa's Best No-Lye Dual Conditioning Relaxer ...                                  0.0   

                                                    2x Ultra Era with Oxi Booster, 50fl oz  \
name                                                                                         
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                     0.0   
100:Complete First Season (blu-Ray)                                                    0.0   
2x Ultra Era with Oxi Booster, 50fl oz                                                 0.0   
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                      0.0   
Africa's Best No-Lye Dual Conditioning Relaxer ...                                     0.0   

                                                    4C Grated Parmesan Cheese 100% Natural 8oz Shaker  \
name                                                                                                    
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                                0.0   
100:Complete First Season (blu-Ray)                                                               0.0   
2x Ultra Era with Oxi Booster, 50fl oz                                                            0.0   
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                                 0.0   
Africa's Best No-Lye Dual Conditioning Relaxer ...                                                0.0   

                                                    Africa's Best No-Lye Dual Conditioning Relaxer System Super  \
name                                                                                                              
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                                0.0             
100:Complete First Season (blu-Ray)                                                               0.0             
2x Ultra Era with Oxi Booster, 50fl oz                                                            0.0             
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                                 0.0             
Africa's Best No-Lye Dual Conditioning Relaxer ...                                                1.0             

                                                    All,bran Complete Wheat Flakes, 18 Oz.  \
name                                                                                         
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                     0.0   
100:Complete First Season (blu-Ray)                                                    0.0   
2x Ultra Era with

In [85]:
item_correlation_df_3[item_correlation_df_3<0]=0

common_item_predicted_ratings = np.dot(item_correlation_df_3, common_item_based_matrix.fillna(0))
common_item_predicted_ratings


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.02151007, 0.        , 0.00063352, ..., 0.00025341, 0.00063352,
        0.00050682],
       [0.        , 0.00355447, 0.00145476, ..., 0.00058191, 0.00145476,
        0.00116381],
       [0.        , 0.01537865, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [86]:
common_item_predicted_ratings.shape

(176, 8250)

In [87]:
dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='name', values='reviews_rating').T.fillna(0)

common_item_predicted_ratings = np.multiply(common_item_predicted_ratings,dummy_test)

The products not rated is marked as 0 for evaluation. And make the item- item matrix representaion.


In [88]:
common_ = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating').T

In [89]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_item_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:461: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:462: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [90]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [91]:
rmse = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse)

3.555309171510971
